name: Setup Env
description: Setup Nix and Go caches
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Load dependencies
      shell: bash
      run: nix develop --impure --command true
    - name: Go environment
      id: go-env
      shell: bash
      run: |
        echo "GOCACHE=$(nix develop --impure --command go env GOCACHE)" >> "$GITHUB_OUTPUT"
        echo "GOMODCACHE=$(nix develop --impure --command go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
    - uses: actions/cache@v5
      with:
        path: |
          ${{ steps.go-env.outputs.GOCACHE }}
          ${{ steps.go-env.outputs.GOMODCACHE }}
          ~/.cache/golangci-lint
        key: ${{ runner.os }}-${{ github.job }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.job }}-go-
